// Generated by LiveScript 1.2.0
(function(){
  var fs, bpcs;
  fs = require('fs');
  bpcs = {};
  module.exports = {
    makeBpc: function(docName){
      var code;
      if (!bpcs[docName]) {
        bpcs[docName] = true;
        code = this.complie({
          docName: docName
        });
        fs.appendFileSync('src/main.ls', code);
      }
    },
    complie: function(context){
      return this.compileBpInitialCode.call(context, context);
    },
    compileBpInitialCode: function(){
      return "new BP.Component '" + this.docName + "'";
    }
  };
}).call(this);
