// Generated by LiveScript 1.2.0
(function(){
  var View;
  View = (function(){
    View.displayName = 'View';
    var prototype = View.prototype, constructor = View;
    View.registry = {};
    View.getView = function(docName, viewName, templateName, type){
      if (this.registry[viewName]) {
        throw new Error("view: '" + viewName + "' already exists");
      }
      return this.registry[viewName] = new View(docName, viewName, templateName, type);
    };
    function View(docName, name, templateName, type){
      this.docName = docName;
      this.name = name;
      this.templateName = templateName;
      this.type = type;
      this.isMainNav = false;
      this.composedViews = {};
    }
    return View;
  }());
  /* ------------------------ Private Methods ------------------- */
  if (typeof module != 'undefined' && module !== null) {
    module.exports = {
      View: View
    };
  } else {
    this.BP._View = View;
  }
}).call(this);
