// Generated by LiveScript 1.2.0
(function(){
  var fs, sugar, Router, BP, views;
  if (module) {
    fs = require('fs');
    sugar = require('sugar');
    Router = require('./Router');
  }
  BP || (BP = {});
  BP.Router || (BP.Router = Router);
  debugger;
  BP.Router.addRouteForViews(views = {
    "assignments-list": {
      "docName": "assignment",
      "name": "assignments-list",
      "type": "list",
      "path": {
        "destinationViewName": "assignments-list",
        "type": "list",
        "composedPaths": []
      },
      "isMainNav": true,
      "composedViews": {},
      "entraces": [],
      "gotos": []
    },
    "assignment": {
      "docName": "assignment",
      "name": "assignment",
      "type": "detail",
      "path": {
        "destinationViewName": "assignment",
        "type": "detail",
        "composedPaths": []
      },
      "isMainNav": false,
      "composedViews": {
        "ref-assignments-list": "assignments-list"
      },
      "entraces": [],
      "gotos": []
    }
  });
}).call(this);
