// Generated by LiveScript 1.2.0
(function(){
  var Names;
  Names = (function(){
    Names.displayName = 'Names';
    var prototype = Names.prototype, constructor = Names;
    function Names(docName){}
    return Names;
  }());
  if (module) {
    module.exports = Names;
  } else {
    BP.Names = Names;
  }
}).call(this);
