// Generated by LiveScript 1.2.0
(function(){
  var fs, View, BP, Router;
  if (module) {
    fs = require('fs');
    View = require('./navigation').View;
  }
  BP || (BP = {});
  BP.View || (BP.View = View);
  Router = (function(){
    Router.displayName = 'Router';
    var prototype = Router.prototype, constructor = Router;
    Router.addRouteForViews = function(views){
      BP.View.resumeViews(views);
      BP.View.createAllViewsPathPattern();
    };
    function Router(){}
    return Router;
  }());
  if (module) {
    module.exports = Router;
  } else {
    BP.Router = Router;
  }
}).call(this);
