// Generated by LiveScript 1.2.0
(function(){
  var registry;
  registry = {};
  module.exports = {
    init: function(namespace, docName){
      var ref$;
      registry[namespace] || (registry[namespace] = {});
      return (ref$ = registry[namespace])[docName] || (ref$[docName] = {
        table: {
          viewRowLinks: [],
          viewRowMultipleLinks: [],
          viewTableLinks: [],
          viewRemovedLinks: [],
          pageAddedRowLinks: [],
          pageAddedRowMultipleLinks: [],
          pageAddedTableLinks: [],
          pageAddedRemovedLinks: []
        }
      });
    },
    getConfig: function(namespace, docName){
      return registry[namespace][docName];
    },
    addItemLink: function(namespace, docName, link){
      return this._addLink(namespace, docName, 'row-links', link);
    },
    addItemLinks: function(namespace, docName, link){
      return this._addLink(namespace, docName, 'row-multiple-links', link);
    },
    addListLink: function(namespace, docName, link){
      return this._addLink(namespace, docName, 'table-links', link);
    },
    removeLink: function(namespace, docName, linkName){
      return this._addLink(namespace, docName, 'removed-links', linkName);
    },
    _addLink: function(namespace, docName, configItemName, link){
      configItemName = this.isPageAdded(link)
        ? 'pageAdded' + configItemName.camelize()
        : 'view' + configItemName.camelize();
      return registry[namespace][docName].table[configItemName].push(link);
    },
    isPageAdded: function(link){
      return !!link.pageName;
    }
  };
}).call(this);
