// Generated by LiveScript 1.2.0
(function(){
  var fs, View, Names, code;
  fs = require('fs');
  View = require('./_view').View;
  Names = require('./Names');
  module.exports = {
    getView: function(docName, viewName, templateName, templateType){
      return View.getView.apply(View, arguments);
    },
    setMainNav: function(templateNames){
      var i$, len$, name, results$ = [];
      if (typeof templateNames === 'string') {
        templateNames = templateNames.split(',');
      }
      for (i$ = 0, len$ = templateNames.length; i$ < len$; ++i$) {
        name = templateNames[i$];
        name = name.trim();
        results$.push(View.registry[name].isMainNav = true);
      }
      return results$;
    },
    setListClassName: function(listClassName){
      this.listClassName = listClassName;
      return console.log("class-name: ", this.listClassName);
    },
    saveView: function(view){
      fs.writeFileSync('bp/main.ls', code + JSON.stringify(View.registry) + (this.listClassName ? ", '" + this.listClassName.camelize() + "', 'list'" : ''));
    },
    getRefName: function(ref){
      switch (ref) {
      case 'detail':
        return this.names.detailTemplateName;
      case 'list':
        return this.names.listTemplateName;
      default:
        return ref;
      }
    },
    getNames: function(docName){
      return this.names = new Names(docName);
    },
    getTableRowAddtionalLinks: function(links){
      var results, path, config;
      results = [];
      for (path in links) {
        config = links[path];
        if (config.at === 'row') {
          results.push({
            path: path,
            icon: config.icon,
            guard: config.guard
          });
        }
      }
      return results;
    }
  };
  code = ' \n# ********************************************************\n# *                                                      *\n# *        IT IS AUTO GENERATED DON\'T EDIT               *\n# *                                                      *\n# ********************************************************\n\n# if module?\n#   require! [fs, sugar, \'./Component\'] \n\n# BP ||= {}\n# BP.Component ||= Component\n\n# debugger\nBP.Component.create-components-from-jade-views jade-views = ';
}).call(this);
