// Generated by LiveScript 1.2.0
(function(){
  var View;
  View = (function(){
    View.displayName = 'View';
    var prototype = View.prototype, constructor = View;
    View.registry = {};
    View.getView = function(docName, namespace, templateName, type){
      if (this.registry[templateName]) {
        throw new Error("view: '" + templateName + "' already exists");
      }
      return this.registry[templateName] = new View(docName, namespace, templateName, type);
    };
    function View(docName, namespace, templateName, type){
      this.docName = docName;
      this.namespace = namespace;
      this.templateName = templateName;
      this.type = type;
      this.name = this.templateName;
      this.isMainNav = false;
      this.referredViews = {};
    }
    return View;
  }());
  this.BP || (this.BP = {});
  if (typeof module != 'undefined' && module !== null) {
    module.exports = {
      View: View
    };
  } else {
    this.BP._View = View;
  }
}).call(this);
