// Generated by LiveScript 1.2.0
(function(){
  var Names;
  Names = (function(){
    Names.displayName = 'Names';
    var prototype = Names.prototype, constructor = Names;
    function Names(docName){
      var _baseRouteName, _baseRoutePath;
      import$(this, {
        docName: docName,
        mongoCollectionName: docName.pluralize(),
        meteorCollectionName: docName.pluralize().capitalize(),
        listTemplateName: docName.pluralize() + '-list',
        listDataRetrieverName: docName.pluralize(),
        detailTemplateName: docName,
        detailDataRetrieverName: docName,
        listDataPublishName: docName.pluralize().capitalize(),
        detailDataPublishName: docName.capitalize()
      });
      _baseRouteName = docName.pluralize();
      _baseRoutePath = '/' + docName.pluralize();
    }
    return Names;
  }());
  if (typeof module != 'undefined' && module !== null) {
    module.exports = Names;
  } else {
    BP.Names = Names;
  }
  function import$(obj, src){
    var own = {}.hasOwnProperty;
    for (var key in src) if (own.call(src, key)) obj[key] = src[key];
    return obj;
  }
}).call(this);
