// Generated by LiveScript 1.2.0
(function(){
  var Names;
  Names = (function(){
    Names.displayName = 'Names';
    var prototype = Names.prototype, constructor = Names;
    function Names(namespace, docName){
      this.componentPrefix = namespace === 'default'
        ? ''
        : namespace + '-';
      this.docName = docName;
      this.mongoCollectionName = docName.pluralize();
      this.meteorCollectionName = docName.pluralize().capitalize();
      this.listTemplateName = this.componentPrefix + docName.pluralize() + '-list';
      this.listRowTemplateName = this.componentPrefix + docName.pluralize() + '-list-row';
      this.listDataRetrieverName = this.componentPrefix + docName.pluralize();
      this.detailTemplateName = this.componentPrefix + docName;
      this.detailDataRetrieverName = this.componentPrefix + docName;
      this.listDataPublishName = this.componentPrefix + docName.pluralize().capitalize();
      this.detailDataPublishName = this.componentPrefix + docName.capitalize();
    }
    return Names;
  }());
  if (typeof module != 'undefined' && module !== null) {
    module.exports = Names;
  } else {
    BP.Names = Names;
  }
}).call(this);
