// Generated by LiveScript 1.2.0
(function(){
  var Relation, replace$ = ''.replace;
  Relation = (function(){
    Relation.displayName = 'Relation';
    var prototype = Relation.prototype, constructor = Relation;
    Relation.registry = {};
    Relation.addRelation = function(namespace, start, relationDescription, end, type){
      var relation;
      relation = new Relation(namespace, start, relationDescription, end, type);
      this._addToRegistryOf(relation.startPoint.docName, relation);
      this._addToRegistryOf(relation.endPoint.docName, relation);
      console.log("Registry is: ", this.registry);
    };
    Relation._addToRegistryOf = function(docName, relation){
      var ref$;
      (ref$ = this.registry)[docName] || (ref$[docName] = []);
      this.registry[docName].push(relation);
    };
    Relation.getRelationsByDocName = function(docName){
      return this.registry[docName] || [];
    };
    function Relation(namespace, startPoint, relationDescription, endPoint, type){
      this.namespace = namespace;
      this.relationDescription = relationDescription;
      this.type = type;
      this.startPoint = this.getPoint(startPoint);
      this.endPoint = this.getPoint(endPoint);
      console.log("******** relation created is: ", this);
    }
    prototype.getPoint = function(config){
      if (typeof config === 'string') {
        return {
          docName: config,
          showName: config
        };
      } else {
        return config;
      }
    };
    prototype.getGoCreateLink = function(currentEnd){
      return this.getLinkByAction('go-create', currentEnd);
    };
    prototype.getGoUpdateLink = function(currentEnd){
      return this.getLinkByAction('go-update', currentEnd);
    };
    prototype.getOppositeEnd = function(currentEnd){
      if (this.startPoint.docName === currentEnd) {
        return this.endPoint;
      } else {
        return this.startPoint;
      }
    };
    prototype.getLinkByAction = function(action, currentEnd){
      var destinationEnd, face, docName, showName, fullDocName, view, link;
      destinationEnd = this.getOppositeEnd(currentEnd);
      face = this.stripGoPrefix(action);
      docName = destinationEnd.docName, showName = destinationEnd.showName;
      fullDocName = this.namespace + '.' + docName;
      view = face === 'list' ? 'list' : 'detail';
      link = {
        icon: action,
        path: action + '-' + fullDocName,
        to: [fullDocName, view, face].join('.'),
        citedDoc: docName,
        citedViewType: view,
        context: docName
      };
      switch (face) {
      case 'create':
        link.label = '创建' + showName;
        link.guard = "!" + docName + "._id";
        delete link.context;
        break;
      case 'update':
        link.label = '更新' + showName;
        link.guard = docName + "";
        break;
      case 'view':
        link.label = '查看' + showName;
        link.guard = view === 'detail' ? docName + "" : 'true';
        break;
      default:
        link.label = face + ': ' + showName;
        link.guard = 'true';
      }
      return link;
    };
    prototype.stripGoPrefix = function(action){
      var face;
      if (action.indexOf('go-') >= 0) {
        face = replace$.call(action, 'go-', '');
      } else {
        face = action;
      }
      if (action === 'go') {
        face = 'list';
      }
      return face;
    };
    prototype.getQuery = function(docName){
      var query;
      if (docName === this.startPoint.docName) {
        return query = "{" + docName + "Id: doc._id}";
      } else {
        return query = "{_id: doc." + this.startPoint.docName + "Id}";
      }
    };
    return Relation;
  }());
  if (typeof module != 'undefined' && module !== null) {
    module.exports = Relation;
  } else {
    BP.Relation = Relation;
  }
}).call(this);
